<?php
return [
    'Company'=>'Компании',
    'LegalEntity'=>'Юр. лица',
    'User'=> 'Пользователи',
    'Role'=>'Роли',
    'Contact'=>'Контакты',
    'Deal'=>'Сделки',
    'Task'=>'Задачи',
    'CashRegister'=>'Кассы',
    'Dds'=>'ДДС',
    'Act'=>'Акты',
    'Room'=>'Комнаты',
    'RoomType'=>'Типы комнат',
    'Smet'=>'Сметы',
    'Employee'=>'Сотрудники',
    'Position'=>'Должности',
    'Work'=>'Работы',
    'WorkCategory'=>'Категории работ',
    'WorkGroup'=>'Группы работ',
    'WorkCollection'=>'Наборы работ',
    'WorkProduct'=>'Расходники для работ',
    'Call'=>'Звонки',
    'Imbox'=>'Чат',
];
